# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 23:03
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name Menu')),
            ],
            options={
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('published', models.BooleanField(verbose_name='Опубликован')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Menu', verbose_name='Меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.MenuItem', verbose_name='Родительский пункт меню')),
            ],
            options={
                'verbose_name_plural': 'Пункты меню',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='Ключевые слова')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок в браузере')),
                ('meta_author', models.CharField(blank=True, max_length=250, verbose_name='Автор сайта')),
                ('favicon_slug', models.CharField(blank=True, max_length=250, verbose_name='Урл favicon')),
                ('published', models.BooleanField(default=0, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name_plural': 'Мета описания',
                'verbose_name': 'Мета описание',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Url pic')),
                ('text1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Text1')),
                ('text2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Text2')),
                ('published', models.BooleanField(verbose_name='Published')),
                ('published_main', models.BooleanField(default='', verbose_name='Published on main')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='content.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Slides',
                'verbose_name': 'Slide',
            },
        ),
        migrations.CreateModel(
            name='Snipet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Код снипета')),
                ('published', models.BooleanField(verbose_name='Опубликован')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name_plural': 'Сниппеты',
                'verbose_name': 'Сниппет',
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('text_small', models.CharField(blank=True, max_length=250, verbose_name='Обещание')),
                ('text_big', models.CharField(blank=True, max_length=250, verbose_name='Заявка на победу')),
                ('published', models.BooleanField(verbose_name='Опубликован')),
            ],
            options={
                'verbose_name_plural': 'Шапки',
                'verbose_name': 'Шапка',
            },
        ),
    ]
