# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-13 00:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='published',
            field=models.BooleanField(verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='favicon_slug',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb favicon'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_author',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe\xd1\x80 \xd1\x81\xd0\xb0\xd0\xb9\xd1\x82\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xb2\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xb2 \xd0\xb1\xd1\x80\xd0\xb0\xd1\x83\xd0\xb7\xd0\xb5\xd1\x80\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='published',
            field=models.BooleanField(default=0, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='name',
            field=models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbe\xd0\xba \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='published',
            field=models.BooleanField(verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='snipet',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4 \xd1\x81\xd0\xbd\xd0\xb8\xd0\xbf\xd0\xb5\xd1\x82\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='top',
            name='published',
            field=models.BooleanField(verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='top',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\xa3\xd1\x80\xd0\xbb'),
        ),
        migrations.AlterField(
            model_name='top',
            name='text_big',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd1\x8f\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xbd\xd0\xb0 \xd0\xbf\xd0\xbe\xd0\xb1\xd0\xb5\xd0\xb4\xd1\x83'),
        ),
        migrations.AlterField(
            model_name='top',
            name='text_small',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x9e\xd0\xb1\xd0\xb5\xd1\x89\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
